apiVersion: v1
kind: Service
metadata:
  name: {{ template "nextflow-api.fullname" . }}
  labels:
    app: {{ template "nextflow-api.name" . }}
    chart: {{ template "nextflow-api.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance }}
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: {{ template "nextflow-api.name" . }}
    instance: {{ .Values.Instance }}
---
{{ if .Values.Ingress.Enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nextflow-api
  labels:
    app: nextflow-api
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: nextflow-api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextflow-api
  annotations:
    kubernetes.io/ingress.class: {{ .Values.Ingress.Class }}
spec:
  rules:
  - host: {{ .Values.Ingress.Host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: nextflow-api
          servicePort: 8080
{{ end }}
